name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_ENVIRONMENT: PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          CIBW_ARCHS_LINUX: "auto64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
